//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdMotivo { get; set; }
        public string Ciclo { get; set; }
        public Nullable<System.TimeSpan> Hora_Iinicio { get; set; }
        public Nullable<System.TimeSpan> Hora_Fin { get; set; }
        public Nullable<int> IdLaboratorio { get; set; }
        public string Novedades { get; set; }
        public string Estado { get; set; }
        public string IdUsuario { get; set; }
    
        public virtual Laboratorio Laboratorio { get; set; }
        public virtual Motivo Motivo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
