//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Auditorias = new HashSet<Auditoria>();
            this.Reservas = new HashSet<Reserva>();
        }
    
        public int Id { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Genero { get; set; }
        public Nullable<int> IdEscuela { get; set; }
        public Nullable<int> IdProfesion { get; set; }
        public string Ttoken { get; set; }
        public string Email { get; set; }
        public Nullable<int> IdRol { get; set; }
        public string Estado { get; set; }
        public string Direccion { get; set; }
        public string Pass { get; set; }
        public string PassOld { get; set; }
        public string ResetCode { get; set; }
        public string Chat_id { get; set; }
        public string Celular { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auditoria> Auditorias { get; set; }
        public virtual Escuela Escuela { get; set; }
        public virtual Parroquia Parroquia { get; set; }
        public virtual Profesion Profesion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reservas { get; set; }
        public virtual Role Role { get; set; }
    }
}
